{% set name = "EditorConfig" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: 8739052279699840065d3a9f5c125d7d5a98daeefe53b0e5274261d77cb49aa2

build:
  number: 0
  noarch: python
  entry_points:
    - editorconfig = editorconfig.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - editorconfig
  commands:
    - pip check
    - editorconfig --help
  requires:
    - pip

about:
  home: http://editorconfig.org/
  summary: EditorConfig File Locator and Interpreter for Python
  license: CNRI-Python
  license_file: COPYING

extra:
  recipe-maintainers:
    - mitchellwood
